void Varibles() {
  BackGroundX1 = width * 0;
  BackGroundY1 = height * 2/3;
  BackGroundWidth1 = width;
  BackGroundHeight1 = height * 1/3;
  BackGroundX2 = width * 2/3;
  BackGroundY2 = height * 0;
  BackGroundWidth2 = width * 1/3;
  BackGroundHeight2 = height;
  BackGroundX3 = width * 0;
  BackGroundY3 = height * 0;
  BackGroundWidth3 = width * 1/50;
  BackGroundHeight3 = height;
  BackGroundWidth4 = width;
  BackGroundHeight4 = height * 1/50;
  DrawingSpaceX = width * 1/50;
  DrawingSpaceY = height * 1/50;
  DrawingSpaceWidth = width * 2/3;
  DrawingSpaceHeight = height * 2/3;
  penbuttonX = width * 4/5;
  penbuttonY = height * 1/5;
  penbuttonWidth = width * 1/9;
  penbuttonHeight = height * 1/9;
  eraserX = width * 3.5/5;
  eraserY =  penbuttonY;
  RectanglebuttonX = penbuttonX; 
  RectanglebuttonY = penbuttonY*3/7;
  eraserbuttonWidth = penbuttonWidth;
  eraserbuttonHeight = penbuttonHeight;
  RectangleWidth = RectangleHeight = height * 1/10;
  eraserWidth = width * 1/20;
  eraserHeight = eraserWidth;
  BluebuttonX = width * 0.1/5;
  GreenbuttonX = width * 0.4/5;
  RedbuttonX = width * 0.7/5;
  WhitebuttonX = width * 1/5;
  OrangebuttonX = width * 1.3/5;
  PurplebuttonX = width * 1.6/5;
  YellowbuttonX = width * 1.9/5;
  BluebuttonY = GreenbuttonY =  RedbuttonY = WhitebuttonY = OrangebuttonY = PurplebuttonY = YellowbuttonY = height * 3.35/5;
  BluebuttonWidth = BluebuttonHeight = penbuttonWidth/2;
  //
  thickness = width * 1/900;
  thicknessbuttonWidth = width * 1/40;
  thicknessbuttonHeight = thicknessbuttonWidth;
  thicknessbuttonY = height * 1/2;
  thicknessbuttonX1 = width * 3/4;
  thicknessbuttonX2 = thicknessbuttonX1 + thicknessbuttonWidth;
  thicknessbuttonX3 = thicknessbuttonX2 + thicknessbuttonWidth;
  thicknessbuttonX4 = thicknessbuttonX3 + thicknessbuttonWidth;
  thicknessbuttonX5 = thicknessbuttonX4 + thicknessbuttonWidth;
  thicknessbuttonX6 = thicknessbuttonX5 + thicknessbuttonWidth;
  thicknessbuttonX7 = thicknessbuttonX6 + thicknessbuttonWidth;
  thicknessbuttonX8 = thicknessbuttonX7 + thicknessbuttonWidth;
  //
}
